CREATE TABLE USER (
	id INT PRIMARY KEY AUTO_INCREMENT,
	User_name VARCHAR(100) NOT NULL UNIQUE,
	Display_name VARCHAR(100) NOT NULL,
	Elo INT NOT NULL DEFAULT 1500,
	Preferred_elo INT NOT NULL DEFAULT 1500
);

CREATE TABLE GAME (
	id INT PRIMARY KEY AUTO_INCREMENT,
	User_id INT NOT NULL,
	Fen VARCHAR(100) NOT NULL DEFAULT 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
	Active BOOLEAN NOT NULL DEFAULT 1,
	Won BOOLEAN NOT NULL DEFAULT 0,

	FOREIGN KEY(User_id) REFERENCES USER(id)
);